Repository crab85193/Tely, pull requests merged in 2023-11, with the labels that each got.

#20 add: ログアウト機能を追加
  main_app/urls.py
  main_app/views/login.py
  main_app/views/logout.py
  templates/main_app/base.html
  templates/main_app/login.html
  templates/main_app/login/base.html
  templates/main_app/login/login.html
  templates/main_app/login/logout.html
Labels: Type: new feature

#22 update: Telyのロゴをサイト内に反映
  static/.DS_Store
  static/css/style.css
  static/img/apple-touch-icon.png
  static/img/favicon.png
  static/img/logo.png
  templates/main_app/base.html
  templates/main_app/login/login.html
  templates/main_app/login/logout.html
Labels: Type: improvement

#24 update: 管理者のみテンプレートファイルにアクセスできるように修正 + 3 Commit
  main_app/urls.py
  main_app/views/dev/__init__.py
  main_app/views/dev/charts.py
  main_app/views/dev/components.py
  main_app/views/dev/forms.py
  main_app/views/dev/icons.py
  main_app/views/dev/pages.py
  main_app/views/dev/tables.py
  main_app/views/template/admin.py
  main_app/views/top.py
  templates/.DS_Store
  templates/main_app/base.html
  templates/main_app/dev/charts-apexcharts.html
  templates/main_app/dev/charts-chartjs.html
  templates/main_app/dev/charts-echarts.html
  templates/main_app/dev/components-accordion.html
  templates/main_app/dev/components-alerts.html
  templates/main_app/dev/components-badges.html
  templates/main_app/dev/components-breadcrumbs.html
  templates/main_app/dev/components-buttons.html
  templates/main_app/dev/components-cards.html
  templates/main_app/dev/components-carousel.html
  templates/main_app/dev/components-list-group.html
  templates/main_app/dev/components-modal.html
  templates/main_app/dev/components-pagination.html
  templates/main_app/dev/components-progress.html
  templates/main_app/dev/components-spinners.html
  templates/main_app/dev/components-tabs.html
  templates/main_app/dev/components-tooltips.html
  templates/main_app/dev/forms-editors.html
  templates/main_app/dev/forms-elements.html
  templates/main_app/dev/forms-layouts.html
  templates/main_app/dev/forms-validation.html
  templates/main_app/dev/icons-bootstrap.html
  templates/main_app/dev/icons-boxicons.html
  templates/main_app/dev/icons-remix.html
  templates/main_app/dev/index.html
  templates/main_app/dev/pages-blank.html
  templates/main_app/dev/pages-contact.html
  templates/main_app/dev/pages-error-404.html
  templates/main_app/dev/pages-faq.html
  templates/main_app/dev/pages-login.html
  templates/main_app/dev/pages-register.html
  templates/main_app/dev/tables-data.html
  templates/main_app/dev/tables-general.html
  templates/main_app/dev/users-profile.html
Labels: Type: improvement

#30 make call test
  main_app/test/call.py
  main_app/test/call_data.json
Labels: Type: new feature

#32 本番環境へmainブランチの内容を自動デプロイするgithub actionsを作成
  .github/workflows/deploy.yml
Labels: Type: improvement

#33 電話発信ページの作成（動作確認済）
  main_app/call_manager.py
  main_app/urls.py
  main_app/views/reservation.py
  requirements.txt
  templates/main_app/base.html
  templates/main_app/index.html
  templates/main_app/reservation/reservation-done.html
  templates/main_app/reservation/reservation.html
Labels: Type: new feature

#36 紹介ページのテンプレート作成
  product_info/css/styles.css
  product_info/img/Tely_display.png
  product_info/img/Tely_logo_1.png
  product_info/img/Tely_logo_3.png
  product_info/img/bg-masthead.jpg
  product_info/index.html
  product_info/js/scripts.js
Labels: 0: help wanted

#40 猫さんが作ったテンプレートをdjangoに反映
  main_app/urls.py
  main_app/views/product_info.py
  static/product_info/css/styles.css
  static/product_info/img/Tely_display.png
  static/product_info/img/Tely_logo_1.png
  static/product_info/img/Tely_logo_3.png
  static/product_info/img/bg-masthead.jpg
  static/product_info/js/scripts.js
  templates/main_app/product_info.html
Labels: Feedback: feature request

#47 本番環境のSSL化
  .gitignore
  containers/https-portal/Dockerfile
  containers/nginx/conf.d/default.conf
  docker-compose.prod.yml
  entrypoint.sh
  tely/settings.py
Labels: Problem: security

#48 ユーザー設定ページの追加
  main_app/urls.py
  main_app/views/user_settings.py
  static/img/profile-img.jpg
  templates/main_app/base.html
  templates/main_app/password_change/password_change.html
  templates/main_app/user-settings.html
Labels: Type: new feature

#51 エラーページの追加
  tely/settings.py
  templates/403.html
  templates/404.html
  templates/500.html
  templates/error/base.html
Labels: Type: improvement

#52 個別ユーザーごとのお知らせ管理用Model & 予約状況管理用Modelの設計と実装
  main_app/admin.py
  main_app/models/reservation.py
  main_app/models/user_notice.py
Labels: Type: new feature

#53 ヘッダーにお知らせ表示機能を追加
  main_app/models/reservation.py
  main_app/models/user_notice.py
  main_app/templatetags/__init__.py
  main_app/templatetags/tags.py
  tely/settings.py
  templates/main_app/base.html
Labels: Type: new feature

#60 add: メンテナンスモードを追加
  .gitignore
  requirements.txt
  shell/maintenance_mode_off.sh
  shell/maintenance_mode_on.sh
  tely/settings.py
  templates/503.html
  templates/error/base.html
Labels: Type: improvement

#66 fix: 本番環境容量圧迫問題対策
  .github/workflows/deploy.yml
Labels: Problem: bug

#69 お店一覧、詳細表示ページを追加 +2
  main_app/call_manager.py
  main_app/models/reservation.py
  main_app/urls.py
  main_app/views/shop.py
  main_app/views/twilio.py
  templates/main_app/base.html
  templates/main_app/shop/shop_detail.html
  templates/main_app/shop/shop_list.html
Labels: Type: new feature

#72 fix: 予約情報入力ページのリンクを修正
  .gitignore
  templates/base.html
  templates/main_app/base.html
  templates/main_app/shop/shop_detail.html
  templates/main_app/shop/shop_list.html
Labels: Problem: bug
